name: GitHub Actions Parallel Run
# 'on':
#   workflow_dispatch: 
on: [push]
    
jobs:
  Test1:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test1
     #   uses: ./.github/workflows
        with:
          command: npm run google
          browser: chrome
          headless: true
          record: false
  Test2:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test1
     #   uses: ./.github/workflows
        with:
          command: npm run amazon
          browser: chrome
          headless: true
          record: false
