name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build application
        run: |
          npm install
          npm run build
          uses: ./.github/workflows/package.json

  test:
    runs-on: ubuntu-latest
    needs: build  # waits for the 'build' job to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # waits for both 'build' and 'test' jobs to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to production
        run: |
          echo "Deploying..."
